// Ogni tema definisce le classi Tailwind per le varie parti della tabella
// e un colore hex per l'export Word

export const THEMES = [
  {
    id: 'classic',
    label: 'Classic',
    header: 'bg-gray-700 text-white',
    headerCell: 'border-gray-600',
    row: 'bg-white',
    rowAlt: 'bg-gray-50',
    cell: 'border-gray-300 text-gray-800',
    title: 'text-gray-800',
    border: 'border-gray-300',
    wordHeaderColor: '374151',
    wordHeaderText: 'FFFFFF',
  },
  {
    id: 'navy',
    label: 'Navy',
    header: 'bg-blue-900 text-white',
    headerCell: 'border-blue-800',
    row: 'bg-white',
    rowAlt: 'bg-blue-50',
    cell: 'border-blue-200 text-gray-800',
    title: 'text-blue-900',
    border: 'border-blue-200',
    wordHeaderColor: '1E3A5F',
    wordHeaderText: 'FFFFFF',
  },
  {
    id: 'forest',
    label: 'Forest',
    header: 'bg-green-800 text-white',
    headerCell: 'border-green-700',
    row: 'bg-white',
    rowAlt: 'bg-green-50',
    cell: 'border-green-200 text-gray-800',
    title: 'text-green-800',
    border: 'border-green-200',
    wordHeaderColor: '166534',
    wordHeaderText: 'FFFFFF',
  },
  {
    id: 'slate',
    label: 'Slate',
    header: 'bg-slate-600 text-white',
    headerCell: 'border-slate-500',
    row: 'bg-white',
    rowAlt: 'bg-slate-50',
    cell: 'border-slate-200 text-gray-800',
    title: 'text-slate-700',
    border: 'border-slate-200',
    wordHeaderColor: '475569',
    wordHeaderText: 'FFFFFF',
  },
  {
    id: 'coral',
    label: 'Coral',
    header: 'bg-orange-600 text-white',
    headerCell: 'border-orange-500',
    row: 'bg-white',
    rowAlt: 'bg-orange-50',
    cell: 'border-orange-200 text-gray-800',
    title: 'text-orange-700',
    border: 'border-orange-200',
    wordHeaderColor: 'EA580C',
    wordHeaderText: 'FFFFFF',
  },
  {
    id: 'purple',
    label: 'Purple',
    header: 'bg-purple-700 text-white',
    headerCell: 'border-purple-600',
    row: 'bg-white',
    rowAlt: 'bg-purple-50',
    cell: 'border-purple-200 text-gray-800',
    title: 'text-purple-700',
    border: 'border-purple-200',
    wordHeaderColor: '7E22CE',
    wordHeaderText: 'FFFFFF',
  },
  {
    id: 'minimal',
    label: 'Minimal',
    header: 'bg-white text-gray-900 border-b-2 border-gray-900',
    headerCell: 'border-b-2 border-gray-900 border-x-0',
    row: 'bg-white',
    rowAlt: 'bg-white',
    cell: 'border-b border-gray-200 border-x-0 text-gray-800',
    title: 'text-gray-900',
    border: 'border-gray-200',
    wordHeaderColor: 'FFFFFF',
    wordHeaderText: '111827',
    noVerticalBorders: true,
  },
  {
    id: 'striped',
    label: 'Striped',
    header: 'bg-gray-900 text-white',
    headerCell: 'border-gray-800',
    row: 'bg-white',
    rowAlt: 'bg-gray-100',
    cell: 'border-gray-200 text-gray-800',
    title: 'text-gray-900',
    border: 'border-gray-200',
    wordHeaderColor: '111827',
    wordHeaderText: 'FFFFFF',
  },
  {
    id: 'sky',
    label: 'Sky',
    header: 'bg-sky-500 text-white',
    headerCell: 'border-sky-400',
    row: 'bg-white',
    rowAlt: 'bg-sky-50',
    cell: 'border-sky-200 text-gray-800',
    title: 'text-sky-600',
    border: 'border-sky-200',
    wordHeaderColor: '0EA5E9',
    wordHeaderText: 'FFFFFF',
  },
  {
    id: 'rose',
    label: 'Rose',
    header: 'bg-rose-600 text-white',
    headerCell: 'border-rose-500',
    row: 'bg-white',
    rowAlt: 'bg-rose-50',
    cell: 'border-rose-200 text-gray-800',
    title: 'text-rose-600',
    border: 'border-rose-200',
    wordHeaderColor: 'E11D48',
    wordHeaderText: 'FFFFFF',
  },
];

export function getTheme(id) {
  return THEMES.find((t) => t.id === id) || THEMES[0];
}
